# Generated by Django 4.2.5 on 2023-11-17 16:41

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='coursefile',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='coursehyperlink',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='coursehyperlink',
            name='url',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='record',
            name='message',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='session',
            name='classroom_address',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='session',
            name='session_type',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='sessionfile',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='sessionhyperlink',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='sessionhyperlink',
            name='url',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='student',
            name='username',
            field=models.CharField(max_length=255, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()]),
        ),
    ]
