# Generated by Django 4.2.5 on 2023-11-15 14:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_record"),
    ]

    operations = [
        migrations.RenameField(
            model_name="student",
            old_name="studnet_id",
            new_name="student_id",
        ),
        migrations.AlterField(
            model_name="record",
            name="time",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
