# Generated by Django 4.2.5 on 2023-11-18 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_session_session_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursehyperlink',
            name='url',
            field=models.URLField(max_length=2048),
        ),
        migrations.AlterField(
            model_name='sessionhyperlink',
            name='url',
            field=models.URLField(max_length=2048),
        ),
    ]
