# Generated by Django 4.2.5 on 2023-11-18 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_coursehyperlink_url_alter_sessionhyperlink_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursefile',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='coursehyperlink',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='sessionfile',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='sessionhyperlink',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
