# Generated by Django 4.2.5 on 2023-11-15 15:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_rename_studnet_id_student_student_id_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="record",
            old_name="student_id",
            new_name="student",
        ),
    ]
