# Generated by Django 4.2.5 on 2023-11-18 04:59

from django.db import migrations, models

import core.models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_alter_coursefile_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coursefile",
            name="file",
            field=models.FileField(
                upload_to=core.models.CourseFile.get_file_path
            ),
        ),
    ]
