# Generated by Django 4.2.5 on 2023-11-18 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_coursefile_file'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='session',
            unique_together={('course', 'id'), ('course', 'start_time')},
        ),
    ]
