# Generated by Django 4.2.5 on 2023-11-18 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_session_unique_together'),
    ]

    operations = [
        migrations.RenameField(
            model_name='session',
            old_name='classroom_address',
            new_name='classroom',
        ),
        migrations.RenameField(
            model_name='session',
            old_name='session_type',
            new_name='type',
        ),
    ]
