# Generated by Django 4.2.5 on 2023-11-18 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_coursefile_created_at_coursefile_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursefile',
            name='last_edit',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='coursehyperlink',
            name='last_edit',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='sessionfile',
            name='last_edit',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='sessionhyperlink',
            name='last_edit',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
